[package]
name = "failure"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
diesel = { version = "2.0", features = ["postgres","r2d2","serde_json"] }
serde_json = "1.0"
dotenv = "0.15"
actix-rt = "2.6"
diesel_json = "0.2.1"
